# Generated by Django 3.2.7 on 2021-10-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusty', '0002_profile_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='statu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
