# Generated by Django 3.2.7 on 2021-10-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusty', '0003_relation_statu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='statu',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
