# Generated by Django 3.2.7 on 2021-10-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rusty', '0004_alter_relation_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='rusty.profile'),
        ),
    ]
